/**
 * The launcher entry points: Camoufox(), NewBrowser(), NewContext().
 *
 * TypeScript twin of pythonlib/camoufox/sync_api.py (and async_api.py, whose
 * names async_api.ts re-exports). The Python library ships a sync and an
 * async variant because Playwright-Python has two APIs; playwright-core has
 * only one (promise-based), so the behaviours of both live here: the
 * no-viewport default, the stock media defaults, CPU-core pinning with its
 * launch lock (async_api), and virtual-display teardown.
 */
import {
	type Browser,
	type BrowserContext,
	type BrowserType,
	firefox,
} from "playwright-core";
import * as cpuAffinity from "./cpu_affinity.js";
import { generateContextFingerprint } from "./fingerprints.js";
import { ensureModel } from "./fpgen/index.js";
import { type ProxyConfig, ProxyHelper, proxyExitGeo } from "./ip.js";
import {
	applyNoViewport,
	attachDesktopOnlyWarning,
	attachNoViewportDefault,
	attachStockMediaDefaults,
	attachVirtualDisplay,
	driverPid,
	type LaunchOptions,
	launchOptions,
	pinnedCoreCount,
	STOCK_MEDIA_DEFAULTS,
	spoofsWindowDimensions,
} from "./utils.js";
import { VirtualDisplay } from "./virtdisplay.js";

export type Headless = boolean | "virtual";

export interface NewBrowserOptions extends Omit<LaunchOptions, "headless"> {
	/** Whether to run the browser headless. On Linux, `"virtual"` runs a real
	 * (non-headless) browser on an Xvfb display instead. */
	headless?: Headless;
	/** A set of launch options generated by `launchOptions()` to use as-is. */
	from_options?: Record<string, any>;
	/** Whether to use a persistent context. */
	persistent_context?: boolean;
	/** Directory for the persistent profile (Playwright's user_data_dir). */
	user_data_dir?: string;
}

/**
 * Launches a Camoufox browser and returns it (Python: `with Camoufox(...) as
 * browser`). Close it with `browser.close()`; a virtual display, if one was
 * spawned, is torn down with it.
 */
export async function Camoufox(
	options: NewBrowserOptions & { persistent_context: true },
): Promise<BrowserContext>;
export async function Camoufox(options?: NewBrowserOptions): Promise<Browser>;
export async function Camoufox(
	options: NewBrowserOptions = {},
): Promise<Browser | BrowserContext> {
	return NewBrowser(firefox, options);
}

/**
 * Launches a new browser instance for Camoufox given a set of launch options.
 *
 * `from_options`: a set of launch options generated by `launchOptions()` to
 * use. `persistent_context`: whether to use a persistent context. Every other
 * option is passed to `launchOptions()`.
 */
export async function NewBrowser(
	playwright: BrowserType,
	options: NewBrowserOptions & { persistent_context: true },
): Promise<BrowserContext>;
export async function NewBrowser(
	playwright: BrowserType,
	options?: NewBrowserOptions,
): Promise<Browser>;
export async function NewBrowser(
	playwright: BrowserType,
	{
		headless,
		from_options,
		persistent_context,
		debug,
		...kwargs
	}: NewBrowserOptions = {},
): Promise<Browser | BrowserContext> {
	let virtualDisplay: VirtualDisplay | null = null;
	let headlessBool: boolean | undefined;
	if (headless === "virtual") {
		virtualDisplay = new VirtualDisplay(debug ?? false);
		kwargs.virtual_display = await virtualDisplay.get();
		headlessBool = false;
	} else {
		headlessBool = headless;
	}

	let fromOptions = from_options;
	try {
		if (!fromOptions || !Object.keys(fromOptions).length) {
			// Opt-in (2026-09-17). Pinning keeps the identity's core count by
			// constraining the browser to that many cores; it costs real CPU,
			// needs a launch lock, and does nothing on macOS. Off, the host's own
			// snapped count is reported, so reported and measurable still agree.
			kwargs.pin_cpu_cores ??= false;
			fromOptions = await launchOptions({
				...kwargs,
				headless: headlessBool,
				debug,
			});
		}
	} catch (error) {
		// A failed launch must not leave the Xvfb process behind.
		virtualDisplay?.kill();
		throw error;
	}

	// Playwright's default viewport deadlocks Juggler when the window is spoofed
	// to a different size (daijro/camoufox#666), so default to no viewport.
	const noViewportDefault = spoofsWindowDimensions(fromOptions);

	// Pin the driver (and so the browser it is about to spawn) to as many cores
	// as the identity reports, so measurable parallelism matches
	// navigator.hardwareConcurrency; the driver gets its cores back afterwards.
	const pinTo = pinnedCoreCount(fromOptions);
	const launch = () =>
		launchWith(
			playwright,
			fromOptions as Record<string, any>,
			Boolean(persistent_context),
			noViewportDefault,
			virtualDisplay,
		);
	try {
		if (!pinTo) {
			return await cpuAffinity.withUnpinnedLaunch(launch);
		}
		const pid = driverPid();
		// The browser inherits the driver's mask at spawn, so two concurrent
		// launches must not interleave pin/restore.
		return await cpuAffinity.withPinLock(async () => {
			const previous = cpuAffinity.pin(pid, pinTo);
			try {
				return await launch();
			} finally {
				cpuAffinity.restore(pid, previous);
			}
		});
	} catch (error) {
		virtualDisplay?.kill();
		throw error;
	}
}

async function launchWith(
	playwright: BrowserType,
	fromOptions: Record<string, any>,
	persistentContext: boolean,
	noViewportDefault: boolean,
	virtualDisplay: VirtualDisplay | null,
): Promise<Browser | BrowserContext> {
	// Persistent context. Python passes user_data_dir inside the options; the
	// JS API takes it positionally. A user_data_dir alone also selects it.
	const userDataDir = fromOptions.user_data_dir ?? fromOptions.userDataDir;
	if (persistentContext || userDataDir !== undefined) {
		let options: Record<string, any> = { ...fromOptions };
		delete options.user_data_dir;
		delete options.userDataDir;
		if (
			noViewportDefault &&
			!("viewport" in options || "noViewport" in options)
		) {
			options = applyNoViewport(options);
		} else if ("noViewport" in options) {
			options = applyNoViewport(options);
		}
		// The persistent context is created by the launch itself, so its media
		// features come from these options rather than from newContext().
		for (const [key, value] of Object.entries(STOCK_MEDIA_DEFAULTS)) {
			if (!(key in options)) options[key] = value;
		}
		const context = await playwright.launchPersistentContext(
			userDataDir ?? "",
			options,
		);
		return attachVirtualDisplay(context, virtualDisplay);
	}

	// Browser
	const browser = await playwright.launch(fromOptions);
	if (noViewportDefault) {
		attachNoViewportDefault(browser);
	}
	attachStockMediaDefaults(browser);
	attachDesktopOnlyWarning(browser);
	return attachVirtualDisplay(browser, virtualDisplay);
}

export interface NewContextOptions extends Record<string, any> {
	/** A fingerprint preset to use. If omitted, fpgen draws a new identity. */
	preset?: Record<string, any>;
	/** Target OS for the drawn identity ("windows", "macos", "linux"). */
	os?: string;
	/** Firefox major version to claim in the UA. Defaults to the browser's own. */
	ff_version?: string;
	/** IPv4 or IPv6 address to spoof for WebRTC ICE candidates. */
	webrtc_ip?: string;
	/** Per-context proxy, in Playwright's format. */
	proxy?: ProxyConfig;
	/** Per-context geolocation. */
	geolocation?: { latitude: number; longitude: number; accuracy?: number };
}

/** Injection point for the proxy exit-IP lookup (tests replace it). */
export const contextDeps = {
	resolveProxyGeo: (proxy: ProxyConfig) =>
		proxyExitGeo(ProxyHelper.asString(proxy)),
};

/** snake_case -> camelCase, as camoufox.server.camel_case does. */
export function camelCase(snake: string): string {
	if (snake.length < 2) return snake;
	const parts = snake.toLowerCase().split("_");
	const joined = parts
		.map((x) => (x ? x[0].toUpperCase() + x.slice(1) : ""))
		.join("");
	return (
		(snake[0] === "_" ? "_" : "") + joined[0].toLowerCase() + joined.slice(1)
	);
}

/**
 * Creates a new browser context with a unique fingerprint identity.
 *
 * Each context gets its own identity (navigator, screen, WebGL, fonts,
 * voices), drawn by fpgen unless a preset is given, with its own audio noise
 * seed. All values are applied via addInitScript so they self-destruct before
 * page scripts can detect them.
 */
export async function NewContext(
	browser: Browser,
	{
		preset,
		os,
		ff_version,
		webrtc_ip,
		proxy,
		geolocation,
		...contextOptions
	}: NewContextOptions = {},
): Promise<BrowserContext> {
	// Python's fpgen loads its model on import; here it is fetched on first use.
	// launchOptions() awaits it, but a browser from connect() or a custom
	// executable never went through launchOptions().
	await ensureModel();

	// The drawn UA carries fpgen's Firefox version, which must not disagree with
	// the browser the page is actually talking to.
	const ffVersion = ff_version || browser.version().split(".", 1)[0];

	// Auto-derive the WebRTC IP and timezone from the proxy's exit IP when they
	// aren't explicitly provided.
	let webrtcIp = webrtc_ip;
	if (proxy && (!webrtcIp || !("timezoneId" in contextOptions))) {
		const [exitIp, timezone] = await contextDeps.resolveProxyGeo(proxy);
		webrtcIp ||= exitIp;
		if (!("timezoneId" in contextOptions)) contextOptions.timezoneId = timezone;
	}

	const fp = generateContextFingerprint({
		preset: preset as any,
		os,
		ff_version: ffVersion,
		webrtc_ip: webrtcIp,
	});

	// Merge the generated context options with user overrides (user wins). They
	// are already Playwright's JS names (userAgent, deviceScaleFactor,
	// timezoneId); re-casing them turned userAgent into `useragent`, which
	// Playwright ignores, so the HTTP User-Agent contradicted navigator's.
	const opts: Record<string, any> = {
		...fp.context_options,
		...contextOptions,
	};
	if (proxy) opts.proxy = proxy;
	if (geolocation) {
		opts.geolocation = geolocation;
		opts.permissions ??= ["geolocation"];
	}

	const context = await browser.newContext(opts);
	await context.addInitScript(
		(fp as any).initScript ?? (fp as any).init_script,
	);
	return context;
}
