# PHASE 5 BUILD CONFIGURATION
base:
  platform: windows
  architecture: x64

phases:
  - name: phase4_setup
    steps:
      - bootstrap
      - compile
      - package
  - name: phase5_integration
    steps:
      - verify_gan_model
      - test_geoip
      - validate_aging

artifacts:
  - path: bin/lucid.exe
    phase: phase4_setup
  - path: genesis/docker-compose.yml
    phase: phase5_integration
  - path: network/xdp_outbound.o
    phase: phase5_integration
