"""Guard: navigator.doNotTrack and navigator.globalPrivacyControl reach the browser.

Both properties are generated by BrowserForge, mapped in browserforge.yml, declared
in settings/properties.json, and placed in CAMOU_CONFIG -- and until this change
nothing applied either one.

doNotTrack was inert in both halves: navigator.doNotTrack read "unspecified" and no
DNT header was sent, whatever the config said.

globalPrivacyControl was worse, because it is read in exactly one place:

    // dom/workers/WorkerNavigator.cpp, via fingerprint-injection.patch
    bool WorkerNavigator::GlobalPrivacyControl() const {
      if (auto value = MaskConfig::GetBool("navigator.globalPrivacyControl"); ...

The main-thread Navigator::GlobalPrivacyControl has no such read, so with
navigator.globalPrivacyControl=true in the config a page saw false while a worker it
spawned saw true. Measured on 152.0.4-beta.30:

    globalPrivacyControl   main=False   worker=True   Sec-GPC=(absent)

navigator.platform read MacIntel on both threads in the same run, so the worker does
inherit the spoofed identity -- the split is specific to GPC. Two routes to one
boolean that a genuine Firefox derives from a single pref, so a page can spawn a
worker and compare without any reference data.

The fix drives the Firefox pref from the config value rather than spoofing a getter,
because one pref moves the JS property, the worker, and the header together. Spoofing
Navigator::GlobalPrivacyControl alone would have swapped a main/worker mismatch for a
JS/header mismatch.

Run with:
    cd pythonlib && python -m pytest tests/test_privacy_prefs.py -v
"""

import json

import pytest

from camoufox.utils import launch_options


def _launch(**kwargs):
    return launch_options(headless=True, i_know_what_im_doing=True, **kwargs)


def _config_of(opts):
    env = opts["env"]
    chunks = sorted(
        (k for k in env if k.startswith("CAMOU_CONFIG_")),
        key=lambda k: int(k.rsplit("_", 1)[1]),
    )
    return json.loads("".join(env[k] for k in chunks))


@pytest.mark.parametrize("target_os", ["windows", "macos", "linux"])
def test_prefs_track_whatever_the_generator_emitted(target_os):
    """Whenever the config carries the property, the pref must mirror it.

    BrowserForge does not emit globalPrivacyControl for every OS -- Windows
    fingerprints omit it entirely -- so this asserts agreement rather than
    presence. When the key is absent the pref is left alone, which is correct:
    MaskConfig::GetBool returns nothing, WorkerNavigator falls through to the
    same pref the main thread reads, and the two threads still agree.
    """
    opts = _launch(os=target_os)
    prefs, config = opts["firefox_user_prefs"], _config_of(opts)

    if "navigator.globalPrivacyControl" in config:
        want = bool(config["navigator.globalPrivacyControl"])
        assert prefs["privacy.globalprivacycontrol.enabled"] is want
        assert prefs["privacy.globalprivacycontrol.functionality.enabled"] is want
    else:
        assert "privacy.globalprivacycontrol.enabled" not in prefs

    if "navigator.doNotTrack" in config:
        want = str(config["navigator.doNotTrack"]) == "1"
        assert prefs["privacy.donottrackheader.enabled"] is want
    else:
        assert "privacy.donottrackheader.enabled" not in prefs


@pytest.mark.parametrize("configured,expected", [(True, True), (False, False)])
def test_gpc_pref_follows_the_config(configured, expected):
    prefs = _launch(config={"navigator.globalPrivacyControl": configured})["firefox_user_prefs"]
    assert prefs["privacy.globalprivacycontrol.enabled"] is expected
    assert prefs["privacy.globalprivacycontrol.functionality.enabled"] is expected


@pytest.mark.parametrize(
    "configured,expected", [("1", True), ("0", False), ("unspecified", False)]
)
def test_dnt_pref_follows_the_config(configured, expected):
    prefs = _launch(config={"navigator.doNotTrack": configured})["firefox_user_prefs"]
    assert prefs["privacy.donottrackheader.enabled"] is expected


def test_caller_prefs_are_not_overridden():
    """merge_into only fills absent keys, so an explicit pref must survive."""
    prefs = _launch(
        config={"navigator.globalPrivacyControl": True, "navigator.doNotTrack": "1"},
        firefox_user_prefs={
            "privacy.globalprivacycontrol.enabled": False,
            "privacy.donottrackheader.enabled": False,
        },
    )["firefox_user_prefs"]
    assert prefs["privacy.globalprivacycontrol.enabled"] is False
    assert prefs["privacy.donottrackheader.enabled"] is False
